// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efitec.Models
{
    public partial class Curso
    {
        public Curso()
        {
            Nota = new HashSet<Nota>();
        }

        public int IdCurso { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Obligatoriedad { get; set; }

        public virtual ICollection<Nota> Nota { get; set; }
    }
}