// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efitec.Models
{
    public partial class Nota
    {
        public int IdNota { get; set; }
        public int IdAlumno { get; set; }
        public int IdCurso { get; set; }
        public decimal PracticaA { get; set; }
        public decimal PracticaB { get; set; }
        public decimal PracticaC { get; set; }
        public decimal Promedio { get; set; }

        public virtual Alumno IdAlumnoNavigation { get; set; }
        public virtual Curso IdCursoNavigation { get; set; }
    }
}